### ISSUE TITLE
Add this package to the list at https://gap-packages.github.io/

### ISSUE THREAD

**Issue by alex-konovalov** [peal/BacktrackKit#20]
We maintain a list of GAP packages with their public repositories at https://gap-packages.github.io/ - would you like this package to be listed there? It's not limited to packages redistributed with GAP - the aim is to list all packages independently of their status. This will help other GAP users and developers to find them.

**Comment by wilfwilson** [comment]
Hi @alex-konovalov, thanks for asking about this. There are several packages that we are working on here, in the `peal` organisation. Although the repositories are public, we're not quite ready to properly tell other people about them, but we will soon. We'll be in touch when we're ready 🙂
